/** Floating worktree-window and Turn-tail review-panel styles. */
export const worktreeStyles = `
.uvf_root{position:fixed;inset:0;z-index:1200;pointer-events:none}
.uvf_win{--uvf-accent:#5b6cff;--uvf-positive:#20a66a;pointer-events:auto;position:fixed;isolation:isolate;display:flex;flex-direction:column;min-width:1px;min-height:1px;overflow:hidden;color:var(--dsw-alias-label-primary,#172033);background:var(--dsw-alias-bg-base,#fff);border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:16px;box-shadow:0 1px 2px rgba(13,22,38,.08),0 18px 48px rgba(13,22,38,.2),0 0 0 1px rgba(255,255,255,.4) inset;transition:border-color .16s ease,box-shadow .16s ease}
.uvf_win:hover{border-color:color-mix(in srgb,var(--uvf-accent) 28%,var(--dsw-alias-border-l2,#dfe3eb));box-shadow:0 2px 5px rgba(13,22,38,.1),0 22px 58px rgba(13,22,38,.24),0 0 0 1px rgba(255,255,255,.5) inset}
.uvf_win[data-interaction]{transition:none;user-select:none}
.uvf_win[data-interaction]::after{content:"";position:absolute;inset:0;z-index:18;background:transparent}
.uvf_win_folded{height:48px!important}
.uvf_win_max{inset:12px!important;width:auto!important;height:auto!important;border-radius:18px;z-index:1300}
.uvf_windowHeader{position:relative;z-index:10;display:flex;align-items:center;gap:10px;height:48px;padding:0 8px 0 10px;flex:none;cursor:grab;touch-action:none;user-select:none;background:#f7f8fb;background:linear-gradient(180deg,color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 96%,#7583ff),color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 92%,#dfe3f5));border-bottom:1px solid color-mix(in srgb,var(--dsw-alias-border-l2,#dfe3eb) 78%,transparent)}
.uvf_win[data-interaction=move] .uvf_windowHeader{cursor:grabbing}.uvf_win_max .uvf_windowHeader{cursor:default}.uvf_win_folded .uvf_windowHeader{border-bottom:0}
.uvf_windowGlyph{display:grid;place-items:center;width:30px;height:30px;flex:none;border-radius:9px;color:#fff;background:linear-gradient(145deg,#7a87ff,#4f5fe7);box-shadow:0 5px 12px rgba(79,95,231,.25)}
.uvf_windowGlyph svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}
.uvf_windowIdentity{display:flex;flex-direction:column;justify-content:center;min-width:0;flex:1;line-height:1.2}
.uvf_windowTitle,.uvf_windowFile{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.uvf_windowTitle{font-size:12.5px;font-weight:650;letter-spacing:.01em;color:var(--dsw-alias-label-primary,#172033)}.uvf_windowFile{margin-top:2px;font-size:10.5px;color:var(--dsw-alias-label-tertiary,#7d8798)}
.uvf_chip{display:inline-flex;align-items:center;gap:6px;flex:none;padding:3px 8px;border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:999px;font-size:10.5px;font-weight:600;line-height:16px;color:var(--dsw-alias-label-secondary,#566174);background:color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 75%,transparent)}
.uvf_pulse,.uvf_dot{position:relative;width:7px;height:7px;border-radius:50%;background:var(--uvf-positive);flex:none}.uvf_pulse::after{content:"";position:absolute;inset:-3px;border-radius:50%;border:1px solid currentColor;opacity:.24;animation:uvf-pulse 2s ease-out infinite}.uvf_chip[data-status=ready]{color:#16784d;border-color:color-mix(in srgb,#20a66a 30%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#20a66a 8%,var(--dsw-alias-bg-base,#fff))}.uvf_chip[data-status=draft]{color:#9a6114;border-color:color-mix(in srgb,#d78b25 34%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#d78b25 9%,var(--dsw-alias-bg-base,#fff))}.uvf_chip[data-status=draft] .uvf_pulse{background:#d78b25}
.uvf_chip[data-status=trunk],.uvf_chip[data-status=loading],.uvf_chip[data-status=unavailable]{color:#566174}.uvf_chip[data-status=trunk] .uvf_pulse,.uvf_chip[data-status=loading] .uvf_pulse,.uvf_chip[data-status=unavailable] .uvf_pulse{background:#7d8798}
@keyframes uvf-pulse{0%{transform:scale(.7);opacity:.35}70%,100%{transform:scale(1.65);opacity:0}}
.uvf_windowControls{display:flex;align-items:center;gap:3px;flex:none}.uvf_windowControl{display:grid;place-items:center;width:28px;height:28px;padding:0;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary,#566174);background:transparent;cursor:pointer;transition:color .12s ease,background .12s ease,transform .12s ease}.uvf_windowControl:hover{color:var(--dsw-alias-label-primary,#172033);background:color-mix(in srgb,var(--dsw-alias-label-primary,#172033) 8%,transparent)}.uvf_windowControl:active{transform:scale(.92)}.uvf_windowControl:focus-visible{outline:2px solid color-mix(in srgb,var(--uvf-accent) 65%,transparent);outline-offset:1px}.uvf_windowControl_danger:hover{color:#d94242;background:rgba(217,66,66,.1)}.uvf_windowControl svg{width:15px;height:15px;fill:none;stroke:currentColor;stroke-width:1.4;stroke-linecap:round;stroke-linejoin:round}
.uvf_windowBody{display:flex;flex:1;min-width:0;min-height:0;flex-direction:column;background:var(--dsw-alias-bg-base,#fff)}.uvf_windowBody[hidden]{display:none}
.uvf_units{display:flex;align-items:center;gap:5px;min-height:36px;padding:5px 9px;border-bottom:1px solid var(--dsw-alias-border-l2,#dfe3eb);overflow-x:auto;scrollbar-width:thin;background:color-mix(in srgb,var(--dsw-alias-bg-base,#fff) 94%,#edf0f8)}
.uvf_unit{display:inline-flex;align-items:center;gap:4px;flex:none;max-width:220px;border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:8px;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-secondary,#566174);font:11px/20px inherit;padding:0 9px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;transition:border-color .12s ease,color .12s ease,background .12s ease}.uvf_unit:hover{border-color:color-mix(in srgb,var(--uvf-accent) 35%,var(--dsw-alias-border-l2,#dfe3eb));color:var(--dsw-alias-label-primary,#172033)}.uvf_unit_on{border-color:color-mix(in srgb,var(--uvf-accent) 55%,var(--dsw-alias-border-l2,#dfe3eb));color:#4554d6;background:color-mix(in srgb,var(--uvf-accent) 9%,var(--dsw-alias-bg-base,#fff));box-shadow:0 0 0 1px color-mix(in srgb,var(--uvf-accent) 10%,transparent) inset}.uvf_unit_icon{font-size:10px;opacity:.82}
.uvf_viewerShell{position:relative;display:flex;flex:1;min-width:0;min-height:0;background:#f1f3f7}.uvf_frame{display:block;flex:1;min-width:0;min-height:0;width:100%;height:100%;border:0;background:var(--dsw-alias-bg-base,#fff)}
.uvf_note{display:flex;flex:1;flex-direction:column;align-items:center;justify-content:center;gap:12px;padding:28px;text-align:center;font-size:12px;color:var(--dsw-alias-label-tertiary,#7d8798)}.uvf_note button{border:1px solid color-mix(in srgb,var(--uvf-accent) 40%,var(--dsw-alias-border-l2,#dfe3eb));border-radius:8px;padding:6px 13px;color:#fff;background:var(--uvf-accent);font:12px/18px inherit;cursor:pointer}
.uvf_resizeHandle{position:absolute;z-index:20;display:block;touch-action:none}.uvf_resize_n,.uvf_resize_s{left:16px;right:16px;height:10px;cursor:ns-resize}.uvf_resize_n{top:0}.uvf_resize_s{bottom:0}.uvf_resize_w,.uvf_resize_e{top:16px;bottom:16px;width:10px;cursor:ew-resize}.uvf_resize_w{left:0}.uvf_resize_e{right:0}.uvf_resize_nw,.uvf_resize_ne,.uvf_resize_sw,.uvf_resize_se{width:18px;height:18px}.uvf_resize_nw{left:0;top:0;cursor:nwse-resize}.uvf_resize_ne{right:0;top:0;cursor:nesw-resize}.uvf_resize_sw{left:0;bottom:0;cursor:nesw-resize}.uvf_resize_se{right:0;bottom:0;cursor:nwse-resize}.uvf_resize_se::after{content:"";position:absolute;right:4px;bottom:4px;width:7px;height:7px;border-right:1.5px solid color-mix(in srgb,var(--dsw-alias-label-tertiary,#7d8798) 58%,transparent);border-bottom:1.5px solid color-mix(in srgb,var(--dsw-alias-label-tertiary,#7d8798) 58%,transparent);border-radius:0 0 2px}
.uvf_panel{--uvf-review-accent:#5b63e8;display:flex;flex-direction:column;width:100%;max-width:1100px;margin:14px auto 6px;overflow:hidden;border:1px solid color-mix(in srgb,var(--uvf-review-accent) 18%,var(--dsw-alias-border-l2,#dfe3eb));border-radius:18px;color:var(--dsw-alias-label-primary,#172033);background:var(--dsw-alias-bg-base,#fff);box-shadow:0 1px 2px rgba(13,22,38,.05),0 14px 40px rgba(13,22,38,.1)}
.uvf_panel_fullscreen{position:fixed;inset:10px;z-index:1400;width:auto;height:auto;max-width:none;margin:0;border-radius:18px;box-shadow:0 28px 90px rgba(13,22,38,.36)}
.uvf_panelHead{display:flex;align-items:center;gap:9px;height:58px;min-height:58px;box-sizing:border-box;padding:7px 10px;flex:none;background:linear-gradient(125deg,color-mix(in srgb,var(--uvf-review-accent) 8%,var(--dsw-alias-bg-base,#fff)),var(--dsw-alias-bg-base,#fff) 48%);border-bottom:1px solid var(--dsw-alias-border-l2,#dfe3eb)}
.uvf_panelGlyph{display:grid;place-items:center;width:32px;height:32px;flex:none;border-radius:9px;color:#fff;background:linear-gradient(145deg,#7279f4,#4d55d5);box-shadow:0 4px 10px rgba(77,85,213,.18)}.uvf_panelGlyph svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}
.uvf_panelIdentity{display:flex;flex:1;min-width:0;flex-direction:column;gap:2px}.uvf_panelTitleRow{display:flex;min-width:0;align-items:center;gap:8px}.uvf_panelTitle,.uvf_panelWorktree,.uvf_panelMeta{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.uvf_panelTitle{flex:none;font-size:13.5px;font-weight:700;line-height:18px}.uvf_panelWorktree{min-width:0;color:var(--uvf-review-accent);font-size:11px;font-weight:600;line-height:16px}.uvf_panelMeta{color:var(--dsw-alias-label-tertiary,#7d8798);font-size:10px;line-height:14px}
.uvf_panelChip{display:inline-flex;align-items:center;gap:6px;flex:none;padding:4px 10px;border:1px solid var(--dsw-alias-border-l2,#dfe3eb);border-radius:999px;font-size:11px;font-weight:650;line-height:16px}.uvf_panelStatusDot{width:7px;height:7px;flex:none;border-radius:50%;background:currentColor}.uvf_panelChip[data-status=ready],.uvf_panelChip[data-status=merged]{color:#16784d;border-color:color-mix(in srgb,#20a66a 32%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#20a66a 9%,var(--dsw-alias-bg-base,#fff))}.uvf_panelChip[data-status=draft]{color:#9a6114;border-color:color-mix(in srgb,#d78b25 34%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#d78b25 9%,var(--dsw-alias-bg-base,#fff))}.uvf_panelChip[data-status=discarded]{color:#697386;border-color:color-mix(in srgb,#7d8798 30%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#7d8798 8%,var(--dsw-alias-bg-base,#fff))}
.uvf_panelChip[data-status=trunk],.uvf_panelChip[data-status=loading],.uvf_panelChip[data-status=unavailable]{color:#697386;border-color:color-mix(in srgb,#7d8798 30%,var(--dsw-alias-border-l2,#dfe3eb));background:color-mix(in srgb,#7d8798 8%,var(--dsw-alias-bg-base,#fff))}
.uvf_panelContent{display:flex;height:min(590px,66dvh);min-height:360px;flex:none;flex-direction:column}.uvf_panelContent[hidden]{display:none}.uvf_panelBody{display:flex;min-height:0;flex:1;flex-direction:column;background:#f1f3f7}.uvf_panelFrame{display:block;width:100%;height:auto;min-height:0;flex:1;border:0;background:var(--dsw-alias-bg-base,#fff)}.uvf_panelUnavailable{display:grid;min-height:0;flex:1;place-items:center;color:var(--dsw-alias-label-tertiary,#7d8798);font-size:12px}.uvf_panel_fullscreen .uvf_panelContent{height:auto;min-height:0;flex:1}.uvf_panel_fullscreen .uvf_panelBody{flex:1}.uvf_panel_fullscreen .uvf_panelFrame{height:auto;min-height:0;flex:1}
.uvf_btn{display:grid;place-items:center;width:32px;height:32px;flex:none;padding:0;border:0;border-radius:9px;color:var(--dsw-alias-label-secondary,#566174);background:transparent;cursor:pointer;transition:color .12s ease,background .12s ease,transform .12s ease}.uvf_btn:hover{color:var(--dsw-alias-label-primary,#172033);background:color-mix(in srgb,var(--dsw-alias-label-primary,#172033) 8%,transparent)}.uvf_btn:active{transform:scale(.92)}.uvf_btn:focus-visible{outline:2px solid color-mix(in srgb,var(--uvf-review-accent) 65%,transparent);outline-offset:1px}.uvf_btn svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.4;stroke-linecap:round;stroke-linejoin:round}
.uvf_panel[data-status=merged]{border-color:color-mix(in srgb,#20a66a 28%,var(--dsw-alias-border-l2,#dfe3eb))}.uvf_panel[data-status=merged] .uvf_panelGlyph{background:linear-gradient(145deg,#2bb373,#16784d);box-shadow:0 7px 16px rgba(22,120,77,.2)}.uvf_panel[data-status=discarded]{border-color:color-mix(in srgb,#7d8798 28%,var(--dsw-alias-border-l2,#dfe3eb));box-shadow:0 1px 2px rgba(13,22,38,.04)}.uvf_panel[data-status=discarded] .uvf_panelGlyph{color:#697386;background:color-mix(in srgb,#7d8798 11%,var(--dsw-alias-bg-base,#fff));box-shadow:none}
.uvf_panel_history{box-shadow:0 1px 2px rgba(13,22,38,.04)}.uvf_panel_history .uvf_panelHead{border-bottom:0}
@media (max-width:680px){.uvf_panel{margin:10px auto 4px;border-radius:14px}.uvf_panel_fullscreen{inset:4px;margin:0;border-radius:14px}.uvf_panelHead{gap:6px;height:54px;min-height:54px;padding:6px}.uvf_panelGlyph{width:30px;height:30px}.uvf_panelIdentity{min-width:0}.uvf_panelTitle{min-width:0;flex:0 1 auto}.uvf_panelWorktree{flex:1}.uvf_panelChip{gap:4px;padding:3px 7px;font-size:10px}.uvf_btn{width:30px;height:30px}.uvf_panelContent{height:min(480px,66dvh);min-height:320px}}
@media (max-width:420px){.uvf_panelGlyph{display:none}.uvf_panelMeta{display:none}.uvf_panelTitleRow{gap:5px}.uvf_panelIdentity{justify-content:center}}
@media (prefers-reduced-motion:reduce){.uvf_win,.uvf_windowControl,.uvf_unit,.uvf_btn{transition:none}.uvf_pulse::after{animation:none}}
`
