/** Lifecycle states persisted by the Univer collaboration service. */
export type WorktreeStatus = 'draft' | 'ready' | 'merged' | 'discarded'

/** How one worktree differs from its trunk baseline. */
export type UnitChangeKind = 'added' | 'modified' | 'deleted' | 'conflict'

/** A changed Univer unit shown in the worktree switcher. */
export interface ChangedUnit {
  readonly unitId: string
  readonly name: string
  readonly type: string | null
  readonly kind: UnitChangeKind
  readonly worktreeUrl?: string
  readonly mergeUrl?: string
}

/** One worktree and the opaque Viewer targets generated by the Host. */
export interface WorktreeState {
  readonly worktreeId: string
  readonly name: string
  readonly status: WorktreeStatus
  readonly units: readonly ChangedUnit[]
  /** Standalone Viewer target used by the turn-tail preview. */
  readonly openUrl?: string
  readonly worktreeUrl?: string
  readonly mergeUrl?: string
}

/** Worktree state rendered while it can still be reviewed or edited. */
export type ActiveWorktreeState = WorktreeState & { readonly status: 'draft' | 'ready' }

/** Current collaboration state for one `.univer` file. */
export interface FileState {
  readonly ok: true
  readonly file: string
  readonly gateway: string | null
  readonly gatewayRunning: boolean
  readonly viewerUrl: string | null
  readonly worktrees: readonly WorktreeState[]
}
